# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# Environment variables (ENV['...']) can be set in the file config/application.yml.
# See http://railsapps.github.io/rails-environment-variables.html
puts 'ROLES'
YAML.load(ENV['ROLES']).each do |role|
  Role.find_or_create_by_name(role)
  puts 'role: ' << role
end
puts 'DEFAULT USERS'
user = User.find_or_create_by_email :name => ENV['ADMIN_NAME'].dup, :email => ENV['ADMIN_EMAIL'].dup, :password => ENV['ADMIN_PASSWORD'].dup, :password_confirmation => ENV['ADMIN_PASSWORD'].dup
puts 'user: ' << user.name
user.add_role :adminActsAsTaggableOn::Tag.create!([
  {name: "hello", taggings_count: 1},
  {name: "world", taggings_count: 1}
])
ActsAsTaggableOn::Tagging.create!([
  {tag_id: 1, taggable_id: 5, taggable_type: "Gestion", tagger_id: nil, tagger_type: nil, context: "gen_freq"},
  {tag_id: 2, taggable_id: 5, taggable_type: "Gestion", tagger_id: nil, tagger_type: nil, context: "gen_freq"}
])
Role.create!([
  {name: "admin", resource_id: nil, resource_type: nil},
  {name: "user", resource_id: nil, resource_type: nil},
  {name: "VIP", resource_id: nil, resource_type: nil}
])
User.create!([
  {email: "user@example.com", encrypted_password: "$2a$10$91Jvy4Moi/JcqvlDqHuqFOCP6R2FF5eg8t/aSX1KmPcmQcViI7HZS", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, name: "First User", structure: nil, fonction: nil, avatar: nil},
  {email: "demo@florileges.info", encrypted_password: "$2a$10$ausVSAcq3UpJM5cdoHenkuvl9BhkpP3508tXyHvDYrLOP1.52VH/C", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 11, current_sign_in_at: "2014-07-03 10:42:42", last_sign_in_at: "2014-07-03 02:55:57", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", name: "Demo", structure: "Démo", fonction: "Démo", avatar: nil},
  {email: "gduhamel.pc@gmail.com", encrypted_password: "$2a$10$E7wMv8LgK6AUFLdb0uhni.bCuTQnfPkLDm4wcJK/xSNj4yJuR8JT6", reset_password_token: "61-JbYMsK9bGzRJQXy4a", reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 5, current_sign_in_at: "2014-08-06 21:15:05", last_sign_in_at: "2014-08-06 20:30:52", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", name: "Gaetan P&C", structure: "P&C", fonction: "TEST", avatar: nil},
  {email: "prairies@florileges.info", encrypted_password: "$2a$10$J4v2YkUrEeg.UXujWxpzgOGLoidEodnpJPnOFC0WxpJDHRTEXzNqG", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2014-07-03 12:00:41", last_sign_in_at: "2014-07-03 10:44:30", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", name: "Admin", structure: "Plante & Cité", fonction: "WebAdmin", avatar: nil},
  {email: "user@florileges.info", encrypted_password: "$2a$10$RrBQ/DrlpqpvAR4/v2I3EuJA2D5w5.yIssr2uov8gR6RB1utRHGaG", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2014-09-07 12:18:09", last_sign_in_at: "2014-06-30 07:16:40", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", name: "User", structure: "USER", fonction: "USER", avatar: nil},
  {email: "gaetan@florileges.info", encrypted_password: "$2a$10$0fzNiB6UxWkRe.7HY9L9ou6uxEtpeobN4NXA8fmlKVp14Yv/iGut.", reset_password_token: "279a13c5865160175321587e4d95070316932a4e6c222c44a87ddb9591bcffab", reset_password_sent_at: "2014-07-08 17:22:39", remember_created_at: nil, sign_in_count: 44, current_sign_in_at: "2014-09-07 19:26:54", last_sign_in_at: "2014-09-07 13:05:14", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", name: "Gaetan", structure: "Plante & Cité", fonction: "Chargé d'études", avatar: nil}
])
Espece.create!([
  {taxref: 91430, bdtfx: nil, famille: "Asteraceae", nom_sci: "Cirsium vulgare", auteur: "(Savi) Ten., 1838", annee: nil, nom_sci_complet: "Cirsium vulgare (Savi) Ten., 1838", nom_vern: "Cirse commun", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "6", flo_i: 3, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 7, tol_pat: 8, tol_pie: 8, off_nec: 3, off_pol: 2, pollen: "Entomogame", hauteur: 600},
  {taxref: 91289, bdtfx: nil, famille: "Asteraceae", nom_sci: "Cirsium arvense", auteur: "(L.) Scop., 1772", annee: nil, nom_sci_complet: "Cirsium arvense (L.) Scop., 1772", nom_vern: "Cirse des champs", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "7", flo_i: 4, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 6, tol_pat: 8, tol_pie: 8, off_nec: 3, off_pol: 2, pollen: "Entomogame", hauteur: 18},
  {taxref: 141165, bdtfx: nil, famille: "Caryophylaceae", nom_sci: "Silene latifolia subsp. Alba", auteur: "(Mill.) Greuter & Burdet, 1982", annee: nil, nom_sci_complet: "Silene latifolia subsp. alba (Mill.) Greuter & Burdet, 1982", nom_vern: "Compagnon blanc", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "6", flo_i: 6, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: nil, tol_pat: nil, tol_pie: nil, off_nec: nil, off_pol: nil, pollen: "Entomogame", hauteur: 60},
  {taxref: 105817, bdtfx: nil, famille: "Asteraceae", nom_sci: "Leucanthemum vulgare", auteur: "Lam., 1779", annee: nil, nom_sci_complet: "Leucanthemum vulgare Lam., 1779", nom_vern: "Marguerite commune", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "6", flo_i: 7, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 4, tol_pat: 3, tol_pie: 4, off_nec: nil, off_pol: nil, pollen: "Entomogame", hauteur: 90},
  {taxref: 85740, bdtfx: nil, famille: "Asteraceae", nom_sci: "Bellis perennis", auteur: "L., 1753", annee: nil, nom_sci_complet: "Bellis perennis L., 1753", nom_vern: "Paquerette", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "1", flo_i: 9, indic_pel: 1, indic_pra: 0, indic_fri: 0, tol_fau: 7, tol_pat: 8, tol_pie: 8, off_nec: nil, off_pol: nil, pollen: "Entomogame", hauteur: 30},
  {taxref: 79908, bdtfx: nil, famille: "Asteraceae", nom_sci: "Achillea millefolium", auteur: "L., 1753", annee: nil, nom_sci_complet: "Achillea millefolium L., 1753", nom_vern: "Achillée millefeuille", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "6", flo_i: 7, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: nil, tol_pat: nil, tol_pie: nil, off_nec: 2, off_pol: 1, pollen: "Entomogame", hauteur: 60},
  {taxref: 94503, bdtfx: nil, famille: "Apiaceae", nom_sci: "Daucus carota", auteur: "L., 1753", annee: nil, nom_sci_complet: "Daucus carota L., 1753", nom_vern: "Carotte sauvage", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "6", flo_i: 4, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 4, tol_pat: 3, tol_pie: 4, off_nec: 3, off_pol: 1, pollen: "Entomogame", hauteur: 50},
  {taxref: 101300, bdtfx: nil, famille: "Apiaceae", nom_sci: "Heracleum sphondylium", auteur: "L., 1753", annee: nil, nom_sci_complet: "Heracleum sphondylium L., 1753", nom_vern: "Berce des prés", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "6", flo_i: 3, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 5, tol_pat: 3, tol_pie: 3, off_nec: 2, off_pol: 2, pollen: "Entomogame", hauteur: 100},
  {taxref: 107886, bdtfx: nil, famille: "Fabaceae", nom_sci: "Melilotus albus", auteur: "Medik., 1787", annee: nil, nom_sci_complet: "Melilotus albus Medik., 1787", nom_vern: "Méliot blanc", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "6", flo_i: 5, indic_pel: 0, indic_pra: 0, indic_fri: 1, tol_fau: 4, tol_pat: 9, tol_pie: 9, off_nec: 3, off_pol: 2, pollen: "Entomogame", hauteur: 40},
  {taxref: 127454, bdtfx: nil, famille: "Fabaceae", nom_sci: "Trifolium repens", auteur: "L., 1753", annee: nil, nom_sci_complet: "Trifolium repens L., 1753", nom_vern: "Trèfle rampant", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "5", flo_i: 7, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 6, tol_pat: 8, tol_pie: 8, off_nec: 3, off_pol: 2, pollen: "Entomogame", hauteur: 90},
  {taxref: 115624, bdtfx: nil, famille: "Rosaceae", nom_sci: "Potentilla reptans", auteur: "L., 1753", annee: nil, nom_sci_complet: "Potentilla reptans L., 1753", nom_vern: "Potentille rampante", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "6", flo_i: 3, indic_pel: 1, indic_pra: 0, indic_fri: 0, tol_fau: 6, tol_pat: 4, tol_pie: 5, off_nec: nil, off_pol: nil, pollen: "Entomogame", hauteur: 50},
  {taxref: 128660, bdtfx: nil, famille: "Scrophulariacea", nom_sci: "Verbascum thapsus", auteur: "L., 1753", annee: nil, nom_sci_complet: "Verbascum thapsus L., 1753", nom_vern: "Molène bouillon-blanc", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "7", flo_i: 4, indic_pel: 0, indic_pra: 0, indic_fri: 1, tol_fau: 4, tol_pat: 4, tol_pie: 4, off_nec: 1, off_pol: 2, pollen: "Autogame", hauteur: 90},
  {taxref: 116903, bdtfx: nil, famille: "Ranunculaceae", nom_sci: "Ranunculus acris", auteur: "L., 1753", annee: nil, nom_sci_complet: "Ranunculus acris L., 1753", nom_vern: "Renoncule acre", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "5", flo_i: 5, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 4, tol_pat: 5, tol_pie: 6, off_nec: nil, off_pol: nil, pollen: "Entomogame", hauteur: 60},
  {taxref: 116952, bdtfx: nil, famille: "Ranunculaceae", nom_sci: "Ranunculus bulbosus", auteur: "L., 1753", annee: nil, nom_sci_complet: "Ranunculus bulbosus L., 1753", nom_vern: "Renoncule bulbeuse", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "5", flo_i: 3, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 4, tol_pat: 5, tol_pie: 4, off_nec: nil, off_pol: nil, pollen: "Entomogame", hauteur: 300},
  {taxref: 117201, bdtfx: nil, famille: "Ranunculaceae", nom_sci: "Ranunculus repens", auteur: "L., 1753", annee: nil, nom_sci_complet: "Ranunculus repens L., 1753", nom_vern: "Renoncule rampante", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "5", flo_i: 3, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 6, tol_pat: 7, tol_pie: 5, off_nec: nil, off_pol: nil, pollen: "Autogame", hauteur: 30},
  {taxref: 106653, bdtfx: nil, famille: "Fabaceae", nom_sci: "Lotus corniculatus", auteur: "L., 1753", annee: nil, nom_sci_complet: "Lotus corniculatus L., 1753", nom_vern: "Lotier corniculé", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "6", flo_i: 4, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 4, tol_pat: 4, tol_pie: 4, off_nec: 2, off_pol: 1, pollen: "Entomogame", hauteur: 60},
  {taxref: 103375, bdtfx: nil, famille: "Asteraceae", nom_sci: "Hypochaeris radicata", auteur: "L., 1753", annee: nil, nom_sci_complet: "Hypochaeris radicata L., 1753", nom_vern: "Porcelle renracinée", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "6", flo_i: 4, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 3, tol_pat: 8, tol_pie: 8, off_nec: nil, off_pol: nil, pollen: "Entomogame", hauteur: 400},
  {taxref: 610646, bdtfx: nil, famille: "Asteraceae", nom_sci: "Jacobaea vulgaris", auteur: "Gaertn., 1791", annee: nil, nom_sci_complet: "Jacobaea vulgaris Gaertn., 1791", nom_vern: "Sénéçon jacobée", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "7", flo_i: 5, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 4, tol_pat: 9, tol_pie: 4, off_nec: 1, off_pol: 2, pollen: "Entomogame", hauteur: 25},
  {taxref: 127029, bdtfx: nil, famille: "Asteraceae", nom_sci: "Tragopogon pratensis", auteur: "L., 1753", annee: nil, nom_sci_complet: "Tragopogon pratensis L., 1753", nom_vern: "Salsifis des prés", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "5", flo_i: 3, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 4, tol_pat: 2, tol_pie: 2, off_nec: nil, off_pol: nil, pollen: "Entomogame", hauteur: 60},
  {taxref: 113474, bdtfx: nil, famille: "Asteraceae", nom_sci: "Picris hieracioides", auteur: "L., 1753", annee: nil, nom_sci_complet: "Picris hieracioides L., 1753", nom_vern: "Picride éperviaire", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "7", flo_i: 5, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 6, tol_pat: 4, tol_pie: 5, off_nec: nil, off_pol: nil, pollen: "Entomogame", hauteur: 70},
  {taxref: 30, bdtfx: nil, famille: "Asteraceae", nom_sci: "Taraxacum ruderalia (Groupe)", auteur: nil, annee: nil, nom_sci_complet: "Taraxacum ruderalia (Groupe)", nom_vern: "Pissenlit", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "3", flo_i: 9, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 6, tol_pat: 7, tol_pie: 5, off_nec: 3, off_pol: 3, pollen: "Entomogame", hauteur: 106},
  {taxref: 112550, bdtfx: nil, famille: "Apiaceae", nom_sci: "Pastinaca sativa", auteur: "L., 1753", annee: nil, nom_sci_complet: "Pastinaca sativa L., 1753", nom_vern: "Panais cultivé", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "7", flo_i: 3, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 7, tol_pat: 8, tol_pie: 8, off_nec: 3, off_pol: 2, pollen: "Entomogame", hauteur: 90},
  {taxref: 82288, bdtfx: nil, famille: "Orchidaceae", nom_sci: "Anacamptis pyramidalis", auteur: "(L.) Rich., 1817", annee: nil, nom_sci_complet: "Anacamptis pyramidalis (L.) Rich., 1817", nom_vern: "Orchis pyramidal", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "6", flo_i: 3, indic_pel: 0, indic_pra: 1, indic_fri: 0, tol_fau: 1, tol_pat: 4, tol_pie: 3, off_nec: nil, off_pol: nil, pollen: "Entomogame", hauteur: 40},
  {taxref: 4, bdtfx: nil, famille: "Asteraceae", nom_sci: "Centaurea jacea  (Groupe)", auteur: nil, annee: nil, nom_sci_complet: "Centaurea  jacea (Groupe)", nom_vern: "Centaurées jacées", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "6", flo_i: 4, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 3, tol_pat: 4, tol_pie: 4, off_nec: 3, off_pol: 2, pollen: "Entomogame", hauteur: 35},
  {taxref: 83499, bdtfx: nil, famille: "Asteraceae", nom_sci: "Arctium lappa", auteur: "L., 1753", annee: nil, nom_sci_complet: "Arctium lappa L., 1753", nom_vern: "Grande bardane", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "7", flo_i: 4, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 3, tol_pat: 9, tol_pie: 9, off_nec: 3, off_pol: 1, pollen: "Autogame", hauteur: 60},
  {taxref: 83502, bdtfx: nil, famille: "Asteraceae", nom_sci: "Arctium minus", auteur: "(Hill) Bernh., 1800", annee: nil, nom_sci_complet: "Arctium minus (Hill) Bernh., 1800", nom_vern: "Bardane à petites tetes", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "7", flo_i: 3, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 6, tol_pat: 5, tol_pie: 5, off_nec: nil, off_pol: nil, pollen: "Entomogame", hauteur: 120},
  {taxref: 127439, bdtfx: nil, famille: "Fabaceae", nom_sci: "Trifolium pratense", auteur: "L., 1753", annee: nil, nom_sci_complet: "Trifolium pratense L., 1753", nom_vern: "Trèfle des prés", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "6", flo_i: 6, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 5, tol_pat: 4, tol_pie: 4, off_nec: 3, off_pol: 2, pollen: "Entomogame", hauteur: 40},
  {taxref: 127314, bdtfx: nil, famille: "Fabaceae", nom_sci: "Trifolium fragiferum", auteur: "L., 1753", annee: nil, nom_sci_complet: "Trifolium fragiferum L., 1753", nom_vern: "Trèfle porte-fraises", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "6", flo_i: 4, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 4, tol_pat: 4, tol_pie: 4, off_nec: 3, off_pol: 2, pollen: "Autogame", hauteur: 30},
  {taxref: 87712, bdtfx: nil, famille: "Campanulaceae", nom_sci: "Campanula rapunculus", auteur: "L., 1753", annee: nil, nom_sci_complet: "Campanula rapunculus L., 1753", nom_vern: "Campanule raiponce", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: nil, flo_i: 4, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: nil, tol_pat: nil, tol_pie: nil, off_nec: nil, off_pol: nil, pollen: "Auto/Ento", hauteur: 60},
  {taxref: 116012, bdtfx: nil, famille: "Lamiaceae", nom_sci: "Prunella vulgaris", auteur: "L., 1753", annee: nil, nom_sci_complet: "Prunella vulgaris L., 1753", nom_vern: "Brunelle commune", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "6", flo_i: 5, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 7, tol_pat: 8, tol_pie: 8, off_nec: 3, off_pol: 2, pollen: "Auto/Ento", hauteur: 150},
  {taxref: 104516, bdtfx: nil, famille: "Dipsacaceae", nom_sci: "Knautia arvensis", auteur: "(L.) Coult., 1828", annee: nil, nom_sci_complet: "Knautia arvensis (L.) Coult., 1828", nom_vern: "Knautie des champs", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "7", flo_i: 6, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 3, tol_pat: 3, tol_pie: 2, off_nec: 2, off_pol: 1, pollen: "Entomogame", hauteur: 100},
  {taxref: 102900, bdtfx: nil, famille: "Poaceae", nom_sci: "Holcus lanatus", auteur: "L., 1753", annee: nil, nom_sci_complet: "Holcus lanatus L., 1753", nom_vern: "Houlque laineuse", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "6", flo_i: 3, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 4, tol_pat: 4, tol_pie: 4, off_nec: nil, off_pol: nil, pollen: "Anémogame", hauteur: 30},
  {taxref: 94207, bdtfx: nil, famille: "Poaceae", nom_sci: "Dactylis glomerata", auteur: "L., 1753", annee: nil, nom_sci_complet: "Dactylis glomerata L., 1753", nom_vern: "Dactyle aggloméré", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "5", flo_i: 6, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 6, tol_pat: 4, tol_pie: 6, off_nec: nil, off_pol: nil, pollen: "Anémogame", hauteur: 150},
  {taxref: 113893, bdtfx: nil, famille: "Plantaginaceae", nom_sci: "Plantago lanceolata", auteur: "L., 1753", annee: nil, nom_sci_complet: "Plantago lanceolata L., 1753", nom_vern: "Plantain lancéolé", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "5", flo_i: 7, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 5, tol_pat: 6, tol_pie: 6, off_nec: nil, off_pol: nil, pollen: "Anémogame", hauteur: 80},
  {taxref: 113904, bdtfx: nil, famille: "Plantaginaceae", nom_sci: "Plantago major", auteur: "L., 1753", annee: nil, nom_sci_complet: "Plantago major L., 1753", nom_vern: "Grand plantain", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "6", flo_i: 5, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 3, tol_pat: 9, tol_pie: 9, off_nec: nil, off_pol: nil, pollen: "Anémogame", hauteur: 100},
  {taxref: 128268, bdtfx: nil, famille: "Urticaceae", nom_sci: "Urtica dioica", auteur: "L., 1753", annee: nil, nom_sci_complet: "Urtica dioica L., 1753", nom_vern: "Ortie dioique", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "7", flo_i: 5, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 6, tol_pat: 7, tol_pie: 5, off_nec: nil, off_pol: nil, pollen: "Entomogame", hauteur: 80},
  {taxref: 119418, bdtfx: nil, famille: "Polygonaceae", nom_sci: "Rumex acetosa", auteur: "L., 1753", annee: nil, nom_sci_complet: "Rumex acetosa L., 1753", nom_vern: "Oseille des prés", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "5", flo_i: 5, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 4, tol_pat: 4, tol_pie: 2, off_nec: nil, off_pol: nil, pollen: "Anémogame", hauteur: 40},
  {taxref: 119550, bdtfx: nil, famille: "Polygonaceae", nom_sci: "Rumex obtusifolius", auteur: "L., 1753", annee: nil, nom_sci_complet: "Rumex obtusifolius L., 1753", nom_vern: "Patience à feuilles obtuses", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "7", flo_i: 3, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 5, tol_pat: 7, tol_pie: 3, off_nec: nil, off_pol: nil, pollen: "Anémogame", hauteur: 30},
  {taxref: 82922, bdtfx: nil, famille: "Poaceae", nom_sci: "Anthoxanthum odoratum", auteur: "L., 1753", annee: nil, nom_sci_complet: "Anthoxanthum odoratum L., 1753", nom_vern: "Flouve odorante", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "5", flo_i: 3, indic_pel: 0, indic_pra: 1, indic_fri: 0, tol_fau: 5, tol_pat: 5, tol_pie: 5, off_nec: nil, off_pol: nil, pollen: "Anémogame", hauteur: 80},
  {taxref: 83912, bdtfx: nil, famille: "Poaceae", nom_sci: "Arrhenatherum elatius", auteur: "(L.) P.Beauv. ex J.Presl & C.Presl, 1819", annee: nil, nom_sci_complet: "Arrhenatherum elatius (L.) P.Beauv. ex J.Presl & C.Presl, 1819", nom_vern: "Fromental élevé", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "6", flo_i: 3, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 4, tol_pat: 3, tol_pie: 3, off_nec: nil, off_pol: nil, pollen: "Anémogame", hauteur: 150},
  {taxref: 106499, bdtfx: nil, famille: "Poaceae", nom_sci: "Lolium perenne", auteur: "L., 1753", annee: nil, nom_sci_complet: "Lolium perenne L., 1753", nom_vern: "Ivraie vivace", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "5", flo_i: 6, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 6, tol_pat: 8, tol_pie: 8, off_nec: nil, off_pol: nil, pollen: "Anémogame", hauteur: 150},
  {taxref: 127660, bdtfx: nil, famille: "Poaceae", nom_sci: "Trisetum flavescens", auteur: "(L.) P.Beauv., 1812", annee: nil, nom_sci_complet: "Trisetum flavescens (L.) P.Beauv., 1812", nom_vern: "Avoine doré", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "5", flo_i: 1, indic_pel: 0, indic_pra: 1, indic_fri: 0, tol_fau: 5, tol_pat: 5, tol_pie: 4, off_nec: nil, off_pol: nil, pollen: "Entomogame", hauteur: 60},
  {taxref: 105247, bdtfx: nil, famille: "Fabaceae", nom_sci: "Lathyrus pratensis", auteur: "L., 1753", annee: nil, nom_sci_complet: "Lathyrus pratensis L., 1753", nom_vern: "Gesse des prés", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "6", flo_i: 3, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 3, tol_pat: 2, tol_pie: 3, off_nec: nil, off_pol: nil, pollen: "Entomogame", hauteur: 75},
  {taxref: 125474, bdtfx: nil, famille: "Asteraceae", nom_sci: "Tanacetum vulgare", auteur: "L., 1753", annee: nil, nom_sci_complet: "Tanacetum vulgare L., 1753", nom_vern: "Tanaisie commune", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "7", flo_i: 4, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 6, tol_pat: 7, tol_pie: 5, off_nec: 1, off_pol: 2, pollen: "Entomogame", hauteur: 40},
  {taxref: 120753, bdtfx: nil, famille: "Rosaceae", nom_sci: "Sanguisorba minor", auteur: "Scop., 1771", annee: nil, nom_sci_complet: "Sanguisorba minor Scop., 1771", nom_vern: "Petite pimprenelle", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "5", flo_i: 5, indic_pel: 0, indic_pra: 0, indic_fri: 0, tol_fau: 2, tol_pat: 4, tol_pie: 5, off_nec: nil, off_pol: nil, pollen: "Anémogame", hauteur: 60},
  {taxref: 90681, bdtfx: nil, famille: "Amaranthaceae", nom_sci: "Chenopodium album", auteur: "L., 1753", annee: nil, nom_sci_complet: "Chenopodium album L., 1753", nom_vern: "Chénopode blanc", avatar: nil, reconnaissance: nil, confusion: nil, habitat_desc: nil, faune: nil, flo_s: "7", flo_i: 5, indic_pel: 0, indic_pra: 0, indic_fri: 1, tol_fau: 7, tol_pat: 9, tol_pie: 9, off_nec: nil, off_pol: nil, pollen: "Anémogame", hauteur: 1000}
])
Gestion.create!([
  {gestion_date: "2014-07-08", gen_prop: "", gen_gest: "", gen_struct: "", gen_surface: nil, gen_freq: "", hist_date: "", hist_desc: "", hist_desc_date: "", it_trav: "", it_amend: "", it_gestion: nil, it_pat_nb: nil, it_pat_duree: "", it_f_cal_prev: "", it_f_cal_current: "", it_p_cal_prev: "", it_p_cal_current: "", it_f_export: nil, it_phyto: nil, it_pression: "", scp_info: nil, scp_desc: "", site_id: 13, gen_obj: "", hist_occsol: "", hist_trav: "", it_trav_freq: "", it_trav_freq_reginfo: "", it_amend_freq: "", it_amend_freq_reginfo: "", it_phyto_info: "", hist_cmt: nil, hist_trav_date: nil, hist_trav_cmt: nil, it_gestion_p: nil, it_gestion_f: nil, gen_struct_name: nil},
  {gestion_date: "2014-07-08", gen_prop: "", gen_gest: "", gen_struct: "", gen_surface: nil, gen_freq: "", hist_date: "", hist_desc: "", hist_desc_date: "", it_trav: "", it_amend: "", it_gestion: nil, it_pat_nb: nil, it_pat_duree: "", it_f_cal_prev: "", it_f_cal_current: "", it_p_cal_prev: "", it_p_cal_current: "", it_f_export: nil, it_phyto: nil, it_pression: "", scp_info: nil, scp_desc: "", site_id: 37, gen_obj: "", hist_occsol: "", hist_trav: "", it_trav_freq: "", it_trav_freq_reginfo: "", it_amend_freq: "", it_amend_freq_reginfo: "", it_phyto_info: "", hist_cmt: nil, hist_trav_date: nil, hist_trav_cmt: nil, it_gestion_p: nil, it_gestion_f: nil, gen_struct_name: nil},
  {gestion_date: "2014-08-07", gen_prop: "", gen_gest: "", gen_struct: "", gen_surface: 130, gen_freq: "Faible", hist_date: "2011", hist_desc: "", hist_desc_date: "", it_trav: "Aucun", it_amend: "Aucun", it_gestion: "\n", it_pat_nb: 23, it_pat_duree: "12", it_f_cal_prev: "juin,Juillet", it_f_cal_current: "Février", it_p_cal_prev: "Novembre,Décembre", it_p_cal_current: "Mars", it_f_export: false, it_phyto: false, it_pression: "Pâturage et terriers par lapins et rongeurs", scp_info: false, scp_desc: "PROPAGE", site_id: 38, gen_obj: "Biodiversité", hist_occsol: "Décharge", hist_trav: "Apport de remblais", it_trav_freq: "Aucun", it_trav_freq_reginfo: "aucun", it_amend_freq: "Aucun", it_amend_freq_reginfo: "aucun", it_phyto_info: "Herbicides", hist_cmt: nil, hist_trav_date: nil, hist_trav_cmt: nil, it_gestion_p: nil, it_gestion_f: nil, gen_struct_name: nil},
  {gestion_date: "2014-08-08", gen_prop: "", gen_gest: "", gen_struct: "", gen_surface: 132, gen_freq: "Faible", hist_date: "2010", hist_desc: "", hist_desc_date: "", it_trav: "Labour", it_amend: "Fumier", it_gestion: nil, it_pat_nb: 12, it_pat_duree: "12", it_f_cal_prev: "Juillet", it_f_cal_current: "Février", it_p_cal_prev: "Août", it_p_cal_current: "Février", it_f_export: false, it_phyto: false, it_pression: "Aucune pression non contrôlée", scp_info: false, scp_desc: "PROPAGES", site_id: 12, gen_obj: "Biodiversité", hist_occsol: "Bâti", hist_trav: "Aucun travaux", it_trav_freq: "", it_trav_freq_reginfo: "", it_amend_freq: "", it_amend_freq_reginfo: "", it_phyto_info: "Anti-mousse", hist_cmt: "", hist_trav_date: "", hist_trav_cmt: "", it_gestion_p: "", it_gestion_f: "", gen_struct_name: ""}
])
Observation.create!([
  {q0: nil, q1: true, q2: false, q3: false, q4: true, q5: false, q6: false, q7: false, q8: true, q9: false, q10: false, p: nil, espece_id: 1, releve_id: 14},
  {q0: nil, q1: false, q2: true, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 7, releve_id: 15},
  {q0: nil, q1: false, q2: true, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 3, releve_id: 15},
  {q0: nil, q1: false, q2: true, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 2, releve_id: 15},
  {q0: nil, q1: false, q2: true, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 7, releve_id: 15},
  {q0: nil, q1: false, q2: true, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 3, releve_id: 15},
  {q0: nil, q1: false, q2: true, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 2, releve_id: 15},
  {q0: nil, q1: true, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 3, releve_id: 16},
  {q0: nil, q1: true, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 2, releve_id: 16},
  {q0: nil, q1: false, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 33, releve_id: 19},
  {q0: nil, q1: false, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 19, releve_id: 19},
  {q0: nil, q1: false, q2: false, q3: false, q4: true, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 3, releve_id: 18},
  {q0: nil, q1: false, q2: true, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 19, releve_id: 18},
  {q0: nil, q1: true, q2: false, q3: true, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: nil, releve_id: 20},
  {q0: nil, q1: false, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: nil, releve_id: 20},
  {q0: nil, q1: true, q2: false, q3: false, q4: true, q5: false, q6: true, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 136673, releve_id: 21},
  {q0: nil, q1: false, q2: true, q3: false, q4: false, q5: true, q6: false, q7: true, q8: false, q9: false, q10: false, p: nil, espece_id: 127029, releve_id: 21},
  {q0: nil, q1: false, q2: false, q3: true, q4: false, q5: false, q6: true, q7: false, q8: true, q9: false, q10: false, p: nil, espece_id: 127660, releve_id: 21},
  {q0: nil, q1: false, q2: false, q3: false, q4: true, q5: false, q6: false, q7: true, q8: false, q9: true, q10: false, p: nil, espece_id: 127660, releve_id: 21},
  {q0: nil, q1: true, q2: true, q3: true, q4: true, q5: true, q6: true, q7: true, q8: true, q9: true, q10: true, p: nil, espece_id: 139574, releve_id: 21},
  {q0: nil, q1: false, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 20, releve_id: 22},
  {q0: nil, q1: false, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 20, releve_id: 22},
  {q0: nil, q1: false, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 15, releve_id: 22},
  {q0: nil, q1: false, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 33, releve_id: 22},
  {q0: nil, q1: false, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 15, releve_id: 23},
  {q0: nil, q1: false, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: nil, releve_id: 23},
  {q0: nil, q1: false, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: nil, releve_id: 23},
  {q0: nil, q1: false, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 25, releve_id: 23},
  {q0: nil, q1: false, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: nil, releve_id: 23},
  {q0: nil, q1: true, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 32, releve_id: 24},
  {q0: nil, q1: true, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 26, releve_id: 24},
  {q0: nil, q1: false, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 32, releve_id: 25},
  {q0: nil, q1: true, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 15, releve_id: 26},
  {q0: nil, q1: false, q2: false, q3: true, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 19, releve_id: 26},
  {q0: nil, q1: false, q2: true, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 20, releve_id: 26},
  {q0: nil, q1: false, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: nil, releve_id: 26},
  {q0: nil, q1: true, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 19, releve_id: 27},
  {q0: nil, q1: true, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 32, releve_id: 27},
  {q0: nil, q1: true, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 20, releve_id: 27},
  {q0: nil, q1: false, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 15, releve_id: 27},
  {q0: nil, q1: false, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 9, releve_id: 27},
  {q0: nil, q1: false, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: nil, releve_id: 28},
  {q0: nil, q1: false, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 27, releve_id: 28},
  {q0: nil, q1: false, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, espece_id: 31, releve_id: 28}
])
Ownership.create!([
  {user_id: 2, site_id: 10, owner: nil},
  {user_id: 2, site_id: 12, owner: nil},
  {user_id: 2, site_id: 13, owner: nil},
  {user_id: 2, site_id: 14, owner: nil},
  {user_id: 2, site_id: 15, owner: nil},
  {user_id: 2, site_id: 16, owner: nil},
  {user_id: 2, site_id: 17, owner: nil},
  {user_id: 2, site_id: 18, owner: nil},
  {user_id: 2, site_id: 19, owner: nil},
  {user_id: 2, site_id: 20, owner: nil},
  {user_id: 2, site_id: 21, owner: nil},
  {user_id: 2, site_id: 23, owner: nil},
  {user_id: 2, site_id: 24, owner: "true"},
  {user_id: 2, site_id: 25, owner: "true"},
  {user_id: 2, site_id: 26, owner: nil},
  {user_id: 2, site_id: 27, owner: nil},
  {user_id: nil, site_id: 27, owner: "true"},
  {user_id: 2, site_id: 28, owner: nil},
  {user_id: nil, site_id: 28, owner: "true"},
  {user_id: 2, site_id: 29, owner: nil},
  {user_id: nil, site_id: 29, owner: "true"},
  {user_id: 2, site_id: 30, owner: nil},
  {user_id: nil, site_id: 31, owner: "true"},
  {user_id: 2, site_id: 31, owner: nil},
  {user_id: nil, site_id: 31, owner: "true"},
  {user_id: nil, site_id: 32, owner: "true"},
  {user_id: 2, site_id: 33, owner: "true"},
  {user_id: 3, site_id: 34, owner: "true"},
  {user_id: 3, site_id: 35, owner: "true"},
  {user_id: 4, site_id: 36, owner: "true"},
  {user_id: 2, site_id: 37, owner: "true"},
  {user_id: 6, site_id: 38, owner: "true"}
])
Releve.create!([
  {date: "2014-07-01", name: "Gaetan", structure: "Plante & Cité", fonction: "Chargé d'études", time_start: "2000-01-01 16:00:00", time_end: "2000-01-01 17:36:00", hauteur: "< 20cm", milieux: "Pelouse,Prairie", user_id: nil, site_id: 13, gestion_id: 29},
  {date: "2014-07-15", name: "Gaetan", structure: "Plante & Cité", fonction: "Chargé d'études", time_start: nil, time_end: nil, hauteur: "", milieux: "Bâti,Prairie", user_id: nil, site_id: 13, gestion_id: 28},
  {date: "2014-07-09", name: "Gaetan", structure: "Plante & Cité", fonction: "Chargé d'études", time_start: "2000-01-01 13:59:00", time_end: nil, hauteur: "", milieux: "", user_id: nil, site_id: 37, gestion_id: 32},
  {date: "2014-07-08", name: "Gaetan", structure: "Plante & Cité", fonction: "Chargé d'études", time_start: nil, time_end: nil, hauteur: "", milieux: "", user_id: nil, site_id: 12, gestion_id: nil},
  {date: "2014-07-09", name: "Gaetan", structure: "Plante & Cité", fonction: "Chargé d'études", time_start: nil, time_end: nil, hauteur: "", milieux: "", user_id: nil, site_id: 12, gestion_id: nil},
  {date: "2014-07-01", name: "Gaetan", structure: "Plante & Cité", fonction: "Chargé d'études", time_start: "2000-01-01 09:20:00", time_end: "2000-01-01 09:20:00", hauteur: "", milieux: "Bâti", user_id: nil, site_id: 12, gestion_id: nil},
  {date: "2014-07-15", name: "Plante et Cité", structure: "Plante & Cité", fonction: "Chargé d'études", time_start: nil, time_end: nil, hauteur: "", milieux: "", user_id: nil, site_id: 12, gestion_id: nil}
])
Site.create!([
  {code: "test", name: "test", parc: "", latitude: "48.00611000000001", longitude: "0.1995560000000296", location: "14 Avenue Pierre Mendès France, 72000 Mans (Le), France", password: nil, topographie: nil, ensoleillement: nil, photo: nil, public: nil, plan: nil},
  {code: "AZERTYUI", name: "Machin", parc: nil, latitude: "47.317739", longitude: "-1.3468760000000657", location: "5001A Rue des Mazères, 44850 Le Cellier, France", password: nil, topographie: "Fort dénivelé (prairie sur talus)", ensoleillement: "Ensoleillé", photo: "DSC06509.JPG", public: nil, plan: "hak88-321.jpg"},
  {code: "RET-4567", name: "Parc Balzac - Prairie#1", parc: "NA", latitude: "47.468433", longitude: "-0.5770469999999932", location: "Angers, France", password: nil, topographie: nil, ensoleillement: nil, photo: "DSC06511.JPG", public: nil, plan: nil},
  {code: "QWERTY", name: "azerty", parc: "azerty", latitude: "48.843657", longitude: "2.3561750000000075", location: "Allée Chevreul, 75005 Paris, France", password: nil, topographie: "", ensoleillement: "", photo: "DSC06509.JPG", public: nil, plan: "DSC06503.JPG"},
  {code: "CG93-006", name: "Prairie fauchée #1", parc: "Parc du sausset", latitude: "48.84321922735556", longitude: "2.3577414100647047", location: "Allée Alfred Lacroix-Edmond Perrier, 75005 Paris, France", password: nil, topographie: "", ensoleillement: "", photo: "DSC06489.JPG", public: nil, plan: "__v_rifier_-_Acer_rubrum__Scanlon___9_.JPG"},
  {code: "003", name: "Plante & Cité", parc: "Blabla", latitude: "47.47978001163983", longitude: "-0.6068718314910484", location: "4 Rue André le Notre, AGROCAMPUS OUEST, 49000 Angers, France", password: nil, topographie: nil, ensoleillement: nil, photo: "DSC06499.JPG", public: nil, plan: nil},
  {code: "AZERTY", name: "kkeh", parc: "azerty", latitude: "47.319470853036975", longitude: "-1.4401655717773565", location: "D209, 44470 Carquefou, France", password: nil, topographie: nil, ensoleillement: nil, photo: "DSC06507.JPG", public: nil, plan: nil},
  {code: "666", name: "Prairie TEST 1", parc: nil, latitude: "47.67723613214278", longitude: "-2.7640579255034936", location: "36 Rue des Paras de la 1ère Bccp, 56000 Vannes, France", password: nil, topographie: "Faible dénivelé", ensoleillement: "Ensoleillé", photo: "3g1W-xE2RC2inh-JSgkIWd05La4.jpg", public: nil, plan: "uploads/rSKMBT_C36014070912310.jpg"},
  {code: "456-IYUU", name: "Prairie semée 1", parc: "Parc départemental du sausset", latitude: "43.28985994125842", longitude: "5.41200869873046", location: "419 Rue Saint-Pierre, 13005 Marseille, France", password: nil, topographie: "", ensoleillement: "", photo: "bohrie-prairie.jpg", public: nil, plan: nil}
])
Taxrefobservation.create!([
  {q0: nil, q1: false, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, releve_id: 22, CD_REF: nil, CD_NOM: nil, LB_NOM: "129159", NOM_VALIDE: nil},
  {q0: nil, q1: false, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, releve_id: 22, CD_REF: nil, CD_NOM: nil, LB_NOM: "109372", NOM_VALIDE: nil},
  {q0: nil, q1: false, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, releve_id: 23, CD_REF: nil, CD_NOM: nil, LB_NOM: "129159", NOM_VALIDE: nil},
  {q0: nil, q1: false, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, releve_id: 23, CD_REF: nil, CD_NOM: nil, LB_NOM: "162468", NOM_VALIDE: nil},
  {q0: nil, q1: false, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, releve_id: 23, CD_REF: nil, CD_NOM: nil, LB_NOM: "196984", NOM_VALIDE: nil},
  {q0: nil, q1: true, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, releve_id: 24, CD_REF: nil, CD_NOM: nil, LB_NOM: "+ Pyronia daniellii", NOM_VALIDE: nil},
  {q0: nil, q1: false, q2: true, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, releve_id: 24, CD_REF: nil, CD_NOM: nil, LB_NOM: "Abama ossifraga", NOM_VALIDE: nil},
  {q0: nil, q1: false, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, releve_id: 25, CD_REF: nil, CD_NOM: nil, LB_NOM: "", NOM_VALIDE: nil},
  {q0: nil, q1: true, q2: false, q3: false, q4: false, q5: true, q6: false, q7: true, q8: false, q9: false, q10: false, p: nil, releve_id: 26, CD_REF: nil, CD_NOM: nil, LB_NOM: "Abacosa onobrychioides", NOM_VALIDE: nil},
  {q0: nil, q1: true, q2: true, q3: true, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, releve_id: 26, CD_REF: nil, CD_NOM: nil, LB_NOM: "Racomitrium aciculare", NOM_VALIDE: nil},
  {q0: nil, q1: false, q2: false, q3: true, q4: false, q5: false, q6: false, q7: true, q8: false, q9: false, q10: false, p: nil, releve_id: 26, CD_REF: nil, CD_NOM: nil, LB_NOM: "+ Pyrocydonia", NOM_VALIDE: nil},
  {q0: nil, q1: false, q2: true, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, releve_id: 27, CD_REF: nil, CD_NOM: nil, LB_NOM: "Campanula albicans", NOM_VALIDE: nil},
  {q0: nil, q1: false, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, releve_id: 27, CD_REF: nil, CD_NOM: nil, LB_NOM: "+ Pyrocydonia", NOM_VALIDE: nil},
  {q0: nil, q1: false, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, releve_id: 28, CD_REF: nil, CD_NOM: nil, LB_NOM: "ejrriyiryi", NOM_VALIDE: nil},
  {q0: nil, q1: false, q2: false, q3: false, q4: false, q5: false, q6: false, q7: false, q8: false, q9: false, q10: false, p: nil, releve_id: 28, CD_REF: nil, CD_NOM: nil, LB_NOM: "Chenia leptophylla", NOM_VALIDE: nil}
])
