require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EspecesController do

  # This should return the minimal set of attributes required to create a valid
  # Espece. As you add validations to Espece, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "taxref" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EspecesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all especes as @especes" do
      espece = Espece.create! valid_attributes
      get :index, {}, valid_session
      assigns(:especes).should eq([espece])
    end
  end

  describe "GET show" do
    it "assigns the requested espece as @espece" do
      espece = Espece.create! valid_attributes
      get :show, {:id => espece.to_param}, valid_session
      assigns(:espece).should eq(espece)
    end
  end

  describe "GET new" do
    it "assigns a new espece as @espece" do
      get :new, {}, valid_session
      assigns(:espece).should be_a_new(Espece)
    end
  end

  describe "GET edit" do
    it "assigns the requested espece as @espece" do
      espece = Espece.create! valid_attributes
      get :edit, {:id => espece.to_param}, valid_session
      assigns(:espece).should eq(espece)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Espece" do
        expect {
          post :create, {:espece => valid_attributes}, valid_session
        }.to change(Espece, :count).by(1)
      end

      it "assigns a newly created espece as @espece" do
        post :create, {:espece => valid_attributes}, valid_session
        assigns(:espece).should be_a(Espece)
        assigns(:espece).should be_persisted
      end

      it "redirects to the created espece" do
        post :create, {:espece => valid_attributes}, valid_session
        response.should redirect_to(Espece.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved espece as @espece" do
        # Trigger the behavior that occurs when invalid params are submitted
        Espece.any_instance.stub(:save).and_return(false)
        post :create, {:espece => { "taxref" => "invalid value" }}, valid_session
        assigns(:espece).should be_a_new(Espece)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Espece.any_instance.stub(:save).and_return(false)
        post :create, {:espece => { "taxref" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested espece" do
        espece = Espece.create! valid_attributes
        # Assuming there are no other especes in the database, this
        # specifies that the Espece created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Espece.any_instance.should_receive(:update).with({ "taxref" => "1" })
        put :update, {:id => espece.to_param, :espece => { "taxref" => "1" }}, valid_session
      end

      it "assigns the requested espece as @espece" do
        espece = Espece.create! valid_attributes
        put :update, {:id => espece.to_param, :espece => valid_attributes}, valid_session
        assigns(:espece).should eq(espece)
      end

      it "redirects to the espece" do
        espece = Espece.create! valid_attributes
        put :update, {:id => espece.to_param, :espece => valid_attributes}, valid_session
        response.should redirect_to(espece)
      end
    end

    describe "with invalid params" do
      it "assigns the espece as @espece" do
        espece = Espece.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Espece.any_instance.stub(:save).and_return(false)
        put :update, {:id => espece.to_param, :espece => { "taxref" => "invalid value" }}, valid_session
        assigns(:espece).should eq(espece)
      end

      it "re-renders the 'edit' template" do
        espece = Espece.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Espece.any_instance.stub(:save).and_return(false)
        put :update, {:id => espece.to_param, :espece => { "taxref" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested espece" do
      espece = Espece.create! valid_attributes
      expect {
        delete :destroy, {:id => espece.to_param}, valid_session
      }.to change(Espece, :count).by(-1)
    end

    it "redirects to the especes list" do
      espece = Espece.create! valid_attributes
      delete :destroy, {:id => espece.to_param}, valid_session
      response.should redirect_to(especes_url)
    end
  end

end
