require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WoodsController do

  # This should return the minimal set of attributes required to create a valid
  # Wood. As you add validations to Wood, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "q1" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WoodsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all woods as @woods" do
      wood = Wood.create! valid_attributes
      get :index, {}, valid_session
      assigns(:woods).should eq([wood])
    end
  end

  describe "GET show" do
    it "assigns the requested wood as @wood" do
      wood = Wood.create! valid_attributes
      get :show, {:id => wood.to_param}, valid_session
      assigns(:wood).should eq(wood)
    end
  end

  describe "GET new" do
    it "assigns a new wood as @wood" do
      get :new, {}, valid_session
      assigns(:wood).should be_a_new(Wood)
    end
  end

  describe "GET edit" do
    it "assigns the requested wood as @wood" do
      wood = Wood.create! valid_attributes
      get :edit, {:id => wood.to_param}, valid_session
      assigns(:wood).should eq(wood)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Wood" do
        expect {
          post :create, {:wood => valid_attributes}, valid_session
        }.to change(Wood, :count).by(1)
      end

      it "assigns a newly created wood as @wood" do
        post :create, {:wood => valid_attributes}, valid_session
        assigns(:wood).should be_a(Wood)
        assigns(:wood).should be_persisted
      end

      it "redirects to the created wood" do
        post :create, {:wood => valid_attributes}, valid_session
        response.should redirect_to(Wood.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved wood as @wood" do
        # Trigger the behavior that occurs when invalid params are submitted
        Wood.any_instance.stub(:save).and_return(false)
        post :create, {:wood => { "q1" => "invalid value" }}, valid_session
        assigns(:wood).should be_a_new(Wood)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Wood.any_instance.stub(:save).and_return(false)
        post :create, {:wood => { "q1" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested wood" do
        wood = Wood.create! valid_attributes
        # Assuming there are no other woods in the database, this
        # specifies that the Wood created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Wood.any_instance.should_receive(:update).with({ "q1" => "1" })
        put :update, {:id => wood.to_param, :wood => { "q1" => "1" }}, valid_session
      end

      it "assigns the requested wood as @wood" do
        wood = Wood.create! valid_attributes
        put :update, {:id => wood.to_param, :wood => valid_attributes}, valid_session
        assigns(:wood).should eq(wood)
      end

      it "redirects to the wood" do
        wood = Wood.create! valid_attributes
        put :update, {:id => wood.to_param, :wood => valid_attributes}, valid_session
        response.should redirect_to(wood)
      end
    end

    describe "with invalid params" do
      it "assigns the wood as @wood" do
        wood = Wood.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Wood.any_instance.stub(:save).and_return(false)
        put :update, {:id => wood.to_param, :wood => { "q1" => "invalid value" }}, valid_session
        assigns(:wood).should eq(wood)
      end

      it "re-renders the 'edit' template" do
        wood = Wood.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Wood.any_instance.stub(:save).and_return(false)
        put :update, {:id => wood.to_param, :wood => { "q1" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested wood" do
      wood = Wood.create! valid_attributes
      expect {
        delete :destroy, {:id => wood.to_param}, valid_session
      }.to change(Wood, :count).by(-1)
    end

    it "redirects to the woods list" do
      wood = Wood.create! valid_attributes
      delete :destroy, {:id => wood.to_param}, valid_session
      response.should redirect_to(woods_url)
    end
  end

end
